name: 'terminal_library_isar_scheme'
description: 'A sample command-line application.'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: null
dev_dependencies: 
  lints: '^3.0.0'
  test: '^1.24.0'
repository: 'https://github.com/{main_username_owner}/terminal_library'
homepage: 'https://github.com/{main_username_owner}/terminal_library'
issue_tracker: 'https://github.com/{main_username_owner}/terminal_library/issues'
documentation: 'https://github.com/{main_username_owner}/terminal_library/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
