name: 'terminal_library'
description: 'A Cross Platform Terminal Library Easy Maintaned And Support On Everywhere Platform'
version: '0.0.0'
homepage: 'https://github.com/azkadev/terminal_library'
repository: 'https://github.com/azkadev/terminal_library'
issue_tracker: 'https://github.com/azkadev/terminal_library/issues'
documentation: 'https://github.com/azkadev/terminal_library/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  general_lib: '^0.0.44'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  mason_logger: '^0.2.15'
  collection: '^1.18.0'
  yaml: '^3.1.2'
  yaml_writer: '^2.0.0'
  ffi: '^2.1.3'
  asn1lib: '^1.5.3'
  convert: '^3.1.1'
  meta: '^1.12.0'
  pointycastle: '^3.9.1'
  pinenacl: '^0.6.0'
  quiver: '^3.0.0'
  equatable: '^2.0.3'
  general_lib_flutter: '^0.0.25'
  flutter: 
    sdk: 'flutter'
  zmodem: '^0.0.6'
dev_dependencies: 
  test: '^1.24.0'
  lints: '^4.0.0'
dependency_overrides: 
  pointycastle: '3.8.0'
