name: 'terminal_library'
description: 'A Cross Platform Terminal Library Easy Maintaned And Support On Everywhere Platform'
version: '0.0.6'
homepage: 'https://github.com/azkadev/terminal_library'
repository: 'https://github.com/azkadev/terminal_library'
issue_tracker: 'https://github.com/azkadev/terminal_library/issues'
documentation: 'https://github.com/azkadev/terminal_library/tree/main/docs'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.67'
  path: '^1.9.0'
  io_universe: '^0.0.7'
  mason_logger: '^0.3.1'
  collection: '^1.19.0'
  yaml: '^3.1.3'
  yaml_writer: '^2.0.1'
  ffi: '^2.1.4'
  asn1lib: '^1.5.3'
  convert: '^3.1.1'
  meta: '^1.16.0'
  pointycastle: '^3.9.1'
  pinenacl: '^0.6.0'
  quiver: '^3.0.0'
  equatable: '^2.0.3'
  general_lib_flutter: '^0.0.41'
  flutter:
    sdk: 'flutter'
  zmodem: '^0.0.6'
dev_dependencies:
  test: 'any'
  lints: '^5.0.0'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
project:
  type: ''
