name: 'terminal_library_flutter'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/terminal_library'
repository: 'https://github.com/{main_username_owner}/terminal_library'
issue_tracker: 'https://github.com/{main_username_owner}/terminal_library/issues'
documentation: 'https://github.com/{main_username_owner}/terminal_library/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  general_lib: '^0.0.44'
  general_lib_flutter: '^0.0.25'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  terminal_library: '^0.0.0'
  terminal_library_scheme: '^0.0.0'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: null
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
